apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: company-ingress
  namespace: test
spec:
  rules:
  - host: company.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: company-ui
            port:
              number: 80